"""Full Jira lifecycle integration tests.

Tests against live Jira Cloud instance (PHX project).
Run with: INTEGRATION_TESTS=true pytest tests/integration/ -v -s
"""

import os

import pytest
import pytest_asyncio

from app.integrations.jira_client import JiraClient

pytestmark = pytest.mark.skipif(
    os.environ.get("INTEGRATION_TESTS") != "true",
    reason="Integration tests disabled. Set INTEGRATION_TESTS=true to enable.",
)

PROJECT_KEY = "PHX"


@pytest_asyncio.fixture
async def jira():
    client = JiraClient(
        base_url=os.environ["JIRA_BASE_URL"],
        email=os.environ["JIRA_EMAIL"],
        api_token=os.environ["JIRA_API_TOKEN"],
    )
    yield client
    await client.close()


class TestConnection:
    @pytest.mark.asyncio
    async def test_ping(self, jira):
        assert await jira.ping() is True

    @pytest.mark.asyncio
    async def test_get_myself(self, jira):
        me = await jira.get_myself()
        assert "accountId" in me
        assert "displayName" in me
        print(f"  Connected as: {me['displayName']}")


class TestProjectAccess:
    @pytest.mark.asyncio
    async def test_project_exists(self, jira):
        project = await jira.get_project(PROJECT_KEY)
        assert project is not None
        print(f"  Project: {project['key']} - {project['name']}")

    @pytest.mark.asyncio
    async def test_get_board(self, jira):
        board = await jira.get_board(PROJECT_KEY)
        assert board is not None
        print(f"  Board: {board['id']} - {board['name']}")

    @pytest.mark.asyncio
    async def test_get_project_statuses(self, jira):
        statuses = await jira.get_project_statuses(PROJECT_KEY)
        assert len(statuses) > 0
        names = sorted(set(s["name"] for s in statuses))
        print(f"  Statuses: {names}")


class TestIssueCreation:
    @pytest.mark.asyncio
    async def test_create_story(self, jira):
        issue = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Story",
            summary="[SIM-TEST] Integration test story",
            fields={
                "description": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                        {
                            "type": "paragraph",
                            "content": [
                                {
                                    "type": "text",
                                    "text": "Auto-generated by simulator integration test.",
                                }
                            ],
                        }
                    ],
                }
            },
        )
        assert "key" in issue
        print(f"  Created story: {issue['key']}")

        # Read it back
        read_back = await jira.get_issue(issue["key"])
        assert read_back["fields"]["summary"] == "[SIM-TEST] Integration test story"

    @pytest.mark.asyncio
    async def test_create_bug(self, jira):
        issue = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Bug",
            summary="[SIM-TEST] Integration test bug",
            fields={},
        )
        assert "key" in issue
        print(f"  Created bug: {issue['key']}")

    @pytest.mark.asyncio
    async def test_create_task(self, jira):
        issue = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Task",
            summary="[SIM-TEST] Integration test task",
            fields={},
        )
        assert "key" in issue
        print(f"  Created task: {issue['key']}")


class TestIssueTransitions:
    @pytest.mark.asyncio
    async def test_transition_to_in_progress_and_done(self, jira):
        # Create a fresh issue
        issue = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Task",
            summary="[SIM-TEST] Transition lifecycle test",
            fields={},
        )
        issue_key = issue["key"]
        print(f"  Created: {issue_key}")

        # Get available transitions
        transitions = await jira.get_issue_transitions(issue_key)
        t_names = {t["name"]: t["id"] for t in transitions}
        print(f"  Available transitions: {list(t_names.keys())}")

        # Transition to In Progress
        in_progress_id = t_names.get("In Progress")
        if in_progress_id:
            await jira.transition_issue(issue_key, in_progress_id)
            updated = await jira.get_issue(issue_key)
            status = updated["fields"]["status"]["name"]
            print(f"  After transition: {status}")
            assert status == "In Progress"

            # Get transitions from In Progress
            transitions2 = await jira.get_issue_transitions(issue_key)
            t_names2 = {t["name"]: t["id"] for t in transitions2}
            print(f"  Transitions from In Progress: {list(t_names2.keys())}")

            # Transition to Done
            done_id = t_names2.get("Done")
            if done_id:
                await jira.transition_issue(issue_key, done_id)
                done_issue = await jira.get_issue(issue_key)
                done_status = done_issue["fields"]["status"]["name"]
                print(f"  Final status: {done_status}")
                assert done_status == "Done"
        else:
            print("  WARNING: No 'In Progress' transition found")
            pytest.skip("In Progress transition not available")


class TestComments:
    @pytest.mark.asyncio
    async def test_add_comment(self, jira):
        issue = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Task",
            summary="[SIM-TEST] Comment test",
            fields={},
        )
        comment = await jira.add_comment(
            issue["key"],
            "[Simulator] Test comment from integration test.",
        )
        assert "id" in comment
        print(f"  Added comment {comment['id']} to {issue['key']}")


class TestIssueLinks:
    @pytest.mark.asyncio
    async def test_create_link(self, jira):
        issue1 = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Story",
            summary="[SIM-TEST] Link parent",
            fields={},
        )
        issue2 = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Task",
            summary="[SIM-TEST] Link child",
            fields={},
        )
        # Get available link types
        link_types = await jira.get_issue_link_types()
        type_names = [lt["name"] for lt in link_types]
        print(f"  Link types: {type_names}")

        if "Blocks" in type_names:
            await jira.create_issue_link(
                "Blocks", issue1["key"], issue2["key"]
            )
            print(f"  Linked: {issue1['key']} blocks {issue2['key']}")
        else:
            # Use first available link type
            lt = link_types[0]["name"]
            await jira.create_issue_link(lt, issue1["key"], issue2["key"])
            print(f"  Linked: {issue1['key']} -{lt}-> {issue2['key']}")


class TestSprintOperations:
    @pytest.mark.asyncio
    async def test_sprint_lifecycle(self, jira):
        board = await jira.get_board(PROJECT_KEY)
        if not board:
            pytest.skip("No board found for PHX")
        board_id = board["id"]
        print(f"  Board: {board_id}")

        # Check for existing active sprint
        active = await jira.get_active_sprint(board_id)
        if active:
            print(f"  Active sprint exists: {active['name']} (id={active['id']})")

        # Create a new sprint
        from datetime import UTC, datetime, timedelta

        now = datetime.now(UTC)
        sprint = await jira.create_sprint(
            board_id=board_id,
            name=f"SIM-TEST Sprint {now.strftime('%H:%M')}",
            start_date=now,
            end_date=now + timedelta(days=14),
        )
        print(f"  Created sprint: {sprint['id']} - {sprint['name']}")
        assert "id" in sprint

        # Create issues and add to sprint
        issue = await jira.create_issue(
            project_key=PROJECT_KEY,
            issue_type="Story",
            summary="[SIM-TEST] Sprint story",
            fields={},
        )
        await jira.add_issues_to_sprint(sprint["id"], [issue["key"]])
        print(f"  Added {issue['key']} to sprint {sprint['id']}")


class TestBacklogGeneration:
    """Test generating backlog content and creating issues in Jira."""

    @pytest.mark.asyncio
    async def test_generate_and_create_in_jira(self, jira):
        from app.engine.backlog import TemplateContentGenerator, generate_issues

        issues = await generate_issues(
            count=3,
            team_name="Phoenix",
            content_generator=TemplateContentGenerator(),
        )
        assert len(issues) == 3

        created_keys = []
        for issue_data in issues:
            created = await jira.create_issue(
                project_key=PROJECT_KEY,
                issue_type=issue_data["issue_type"],
                summary=f"[SIM] {issue_data['summary']}",
                fields={
                    "description": {
                        "type": "doc",
                        "version": 1,
                        "content": [
                            {
                                "type": "paragraph",
                                "content": [
                                    {
                                        "type": "text",
                                        "text": issue_data["description"],
                                    }
                                ],
                            }
                        ],
                    }
                },
            )
            created_keys.append(created["key"])
            print(
                f"  Created {issue_data['issue_type']}: {created['key']} "
                f"- {issue_data['summary'][:50]}... ({issue_data['story_points']}pts)"
            )

        assert len(created_keys) == 3
        print(f"  All 3 backlog issues created: {created_keys}")
